const emailTypeEnum =Object.freeze({ 
    STUDENT_APPLICATION_REQUIRES_APPROVAL:1,
    STUDENT_APPLICATION_INVOICE_REQUIRES_APPROVAL:2,
    STUDENT_APPLICATION_PAYMENT_REQUIRES_APPROVAL:3,
})

module.exports ={emailTypeEnum}