const functionNames = Object.freeze({
  updateUniversityDepartmentStatus: "updateUniversityDepartmentStatus",
  getStudentsToNudge: "getStudentsToNudge",
  updateUniversityDepartment: "updateUniversityDepartment",
  setCronConfig: "setCronConfig",
  nonResponsiveStudent: "nonResponsiveStudent",
  averageCalculationsTimer: "averageCalculationsTimer",
  autoNudgeStudents: "autoNudgeStudents",
  postExistingApplication: "postExistingApplication",
  postExpense: "postExpense",
  getStudentExpense: "getStudentExpense",
  nudgeStudents: "nudgeStudents",
  getDeclinedApplications: "getDeclinedApplications",
  getDepartmentsAndUniversity: "getDepartmentsAndUniversity",
  addDepartment: "addDepartment",
  getFaculties: "getFaculties",
  addUniversity: "addUniversity",
  getAllUniversities: "getAllUniversities",
  sendEmailToHod: "inviteHOD",
  updateInvoiceStatus: "updateInvoiceStatus",
  getStudentQuestinnaireResponses: "getStudentQuestinnaireResponses",
  studentQuestionnaireResponses: "student-questionnaire-responses",
  studentFundingYears: "student-funding-years",
  getYearsOfFunding: "getYearsOfFunding",
  getExpensesValues: "getExpensesValues",
  studentExpenseTypes: "student-expense-types",
  getExpenses: "getExpenses",
  uploadAdminDocuments: "uploadAdminDocuments",
  getApplicationDocuments: "getApplicationDocuments",
  uploadPayment: "uploadPayment",
  adminData: "admin-data",
  applicationsReport: "applications-report",
  rejectStudentApplication: "reject-student-application",
  sendEmailsToHods: "sendEmailsToHods",
  updateStudentApplicationStatus: "update-student-application-status",
  getApplicationsDetails: "getApplicationsDetails",
  getYearOfApplications: "getYearOfApplications",
  insertInvoiceStatusHistory: "insertInvoiceStatusHistory",
  updateApplicationAmount: "updateApplicationAmount",
  emailFailedStudentApplication: "emailFailedStudentApplication",
  createAdmin: "createAdmin",
  config: "config",
  updateStudentDocument: "updateStudentDocument",
  autoNudgeExecutives: "autoNudgeExecutives",
  getMaintenance:"getMaintenance",
  sendEmailToExecutive: "sendEmailToExecutive",
  readEmail: "readMail",
  getLastEmailSentTime:"getLastEmailSentTime",
  getReportsData:"getReportsData",
  getConfig:"getConfig",
  setConfig:"setConfig",
  getUniversityCardData:"getUniversityCardData",
  getBursaryTypes: "getBursaryTypes",
  getBusariesSummary: "getBursariesSummary",
  getEventsCardData: "getEventsCardData",
  getEventDetailsByEventId: "getEventDetailsByEventId",
  getInviteeFilters: "getInviteeFilters",
  updateEvent: "updateEvent",
  terminateStudentApplication: "terminateStudentApplication",
  getDeclinedReasons: "getDeclinedReasons",
});

module.exports = functionNames;
