name: Production deployment

on:
  workflow_dispatch:
    inputs:
      apiRunId:
        description: 'Enter **API build workflow** run ID'
        required: true
      swaRunId:
        description: 'Enter **SWA build workflow** run ID: '
        required: true


jobs:
  download_deploy_api:
    runs-on: ubuntu-latest
    name: Download api artifact and deploy to azure
    steps:
      - name: Download api artifact
        id: daa
        uses: actions/download-artifact@v4
        with:
          name: artifact-API
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.apiRunId }}
  
      - name: 'Deploy function app'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'Tester'
          package: ./artifacts/api_release.zip
          publish-profile: ${{ secrets.TESTER_PUBLISH_PROFILE }}
          sku: 'flexconsumption'

  download_deploy_swa:
    runs-on: ubuntu-latest
    needs: download_deploy_api
    name: Download artifacts and deploy to azure
    steps:
      - name: Download swa artifact
        id: dsa
        uses: actions/download-artifact@v4
        with:
          name: artifact-SWA
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.swaRunId }}

      - name: Unzip SWA for deployment
        run: |
          unzip artifacts/swa_release.zip

  FlywayMigration:
    name: Run Flyway Migration
    needs: download_deploy_swa
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        # - name: Continuous Integration Flyway Migration
        #   run: >-
        #       docker run --rm
        #       --volume ${{ github.workspace }}/db/migrations:/flyway/sql:ro
        #       redgate/flyway
        #       -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
        #       -url="${{ secrets.DB_URL_PROD }}"
        #       -user="${{ secrets.DB_USERNAME_PROD }}"
        #       -password="${{ secrets.DB_PASSWORD_PROD }}" migrate