name: Deploy QA API

on:
  workflow_run:
    workflows: [Build and upload API artifacts]
    types: [completed]
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  download_deploy_release:
    runs-on: ubuntu-latest
    name: Download artifacts and deploy to azure
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download api artifact
        id: daa
        uses: actions/download-artifact@v4
        with:
          name: artifact-API
          path: artifacts/
      
      - name: 'Deploy function app'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'web-app'
          slot-name: 'Production'
          package: ./artifacts/api_release.zip
          publish-profile: ${{ secrets.TESTER_PUBLISH_PROFILE }}
