name: Deploy QA SWA

on:
  workflow_run:
    workflows: [Build and upload SWA artifacts]
    types: [completed]
    branches: [main]

jobs:
  download_deploy_release:
    runs-on: ubuntu-latest
    name: Download artifacts and deploy to azure
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download swa artifact
        id: dsa
        uses: actions/download-artifact@v4
        with:
          name: artifact-SWA
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Unzip SWA for deployment
        run: |
          unzip artifacts/swa_release.zip

      - name: 'Deploy static web app'
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          azure_static_web_apps_api_token: 41368c45c58242f15307f14e8cb8a23897ecfbb949c507ea679c4802cd7b05c501-a3d2a434-ad1c-40ee-b770-2ab51f1d7669003091303a332403
          action: "upload"
          app_location: "dist/web-app"
          skip_app_build: true
