name: Create and upload API, SWA and DB releases

on:
  workflow_run:
    workflows: [Production deployment]
    types: [completed]
    branches: [main]

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%Y.%m.%d.%H)
          RELEASE_NAME=Release-$DATE
          gh release create "$RELEASE_NAME" --repo ${{ vars.REPO }}

  create_api_release:
    runs-on: ubuntu-latest
    name: Create and upload API release asset
    needs: prepare_release
    steps:
      - name: Download api artifact
        id: daa
        uses: actions/download-artifact@v4
        with:
          name: artifact-API
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.apiRunId }}
  
      - name: Upload API release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%Y.%m.%d.%H)
          RELEASE_NAME=Release-$DATE
          gh release upload "$RELEASE_NAME" artifacts/api_release.zip --repo ${{ vars.REPO }}

  create_swa_release:
    runs-on: ubuntu-latest
    name: Create and upload SWA release asset
    needs: 
      - create_api_release
      - prepare_release
    steps:
      - name: Download SWA artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-SWA
          path: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.swaRunId }}

      - name: Upload SWA release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%Y.%m.%d.%H)
          RELEASE_NAME=Release-$DATE
          gh release upload "$RELEASE_NAME" artifacts/swa_release.zip --repo ${{ vars.REPO }}

  create_db_release:
    runs-on: ubuntu-latest
    name: Create and upload DB release asset
    needs: 
      - create_swa_release
      - prepare_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip migration scripts
        run: zip db_migrations.zip db/migrations/ -r

      - name: Upload DB release asset
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%Y.%m.%d.%H)
          RELEASE_NAME=Release-$DATE
          gh release upload "$RELEASE_NAME" db_migrations.zip --repo ${{ vars.REPO }}
